### ISSUE TITLE
Unable to run replace-flash-with-toast

### ISSUE THREAD

**Issue by cbisio** [Sage/carbon-codemod#110]
### Current behaviour

It throws an error:

```
developer@devmachine-2-6-1 ~/Development/s1_fao_ui (build-SBS-28946 *)$ npx carbon-codemod replace-flash-with-toast src
npx: installed 258 in 8.992s
jscodeshift --verbose=2 --ignore-pattern=**/node_modules/** --parser=tsx --extensions=tsx,ts,jsx,js --transform /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js /home/developer/Development/s1_fao_ui/src
Processing 120 files... 
Spawning 3 workers...
Sending 40 files to free worker...
Sending 40 files to free worker...
Sending 40 files to free worker...
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.symbol.js'
Require stack:
- /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js
- /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/jscodeshift/src/Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js',
    '/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/jscodeshift/src/Worker.js'
  ]
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.symbol.js'
Require stack:
- /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js
- /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/jscodeshift/src/Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js',
    '/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/jscodeshift/src/Worker.js'
  ]
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.symbol.js'
Require stack:
- /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js
- /home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/jscodeshift/src/Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/transforms/replace-flash-with-toast/replace-flash-with-toast.js',
    '/home/developer/.npm/_npx/15593/lib/node_modules/carbon-codemod/node_modules/jscodeshift/src/Worker.js'
  ]
}
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.299seconds
```

### Expected behaviour

Replace `Flash` component for `Toast`

### Reproducible example

Instruction used: `npx carbon-codemod replace-flash-with-toast src`

### Suggested solution(s)

Update core-js to v3 could be a possible solution

### Additional context

-

### Your environment

Package.json: https://github.com/Sage/s1_fao_ui/blob/9359a9cf792fa9926fcbcca17c1a21bccdb7bde8/package.json

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| react-scripts    |
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by jamime** [comment]
Thanks we've raised this on our backlog and will investigate.
FE-5018

**Comment by grabkowski** [comment]
@cbisio - this kind of error is thrown when the codemod is running in the project folder.
Please run the codemod from the folder that does not contain `package.json` file, e.g.:
`npx carbon-codemod <name-of-codemod> ./<project-folder>/src`

I will update the carbon-codemod readme file soon, to include that information.
