### ISSUE TITLE
Cannot find module 'lodash')

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon-codemod#117]
Hello, when trying to run npx carbon-codemod replace-row-column-with-grid <folder> I get the following error for every file in the directory:

C:\Dev\<anonPath>\SalesOrderLinesGrid.js Transformation error (Cannot find module 'lodash')
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\<anonUser>\AppData\Roaming\npm-cache\_npx\26604\node_modules\carbon-codemod\node_modules\jscodeshift\parser\/tsx.js:11:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (C:\Users\<anonUser>\AppData\Roaming\npm-cache\_npx\26604\node_modules\carbon-codemod\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (C:\Users\<anonUser>\AppData\Roaming\npm-cache\_npx\26604\node_modules\carbon-codemod\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    
    
It then  summarises:
All done.
Results:
59 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 3.391seconds
    
  I have latest version of lodash installed in our app web.confirm and globally. Have tried clearing cache and reinstalling but to no avail. Is there anything you can suggest?
  
  Thanks.

**Comment by grabkowski** [comment]
hi @Chris3y,
looks like you're trying to run the codemod from the project folder.
The codemod should not be run from the folder containing `package.json` file, as it will try to look for dependencies listed in it. You could find that information under the Usage section of our `README` file.

**Comment by Chris3y** [comment]
@grabkowski, I made sure I'm not and still get the issue. Could it be an out of date Jscodeshift dependency?

See: https://github.com/facebook/jscodeshift/issues/451

Looks like this project uses 0.10.0 and they fixed this post 0.13.0
